<?php require_once "head.php" ?>
    <meta name="description" content="uLink is an efficient website to find your internship quickly. Go faster with uLink!" />
    <title>uLink - Home Page</title>
    <link rel="stylesheet" href="./scss/index.css" type="text/css" />
</head>
<body>
    <?php require_once "header.php" ?>
    <main>
        <h1>Welcome to uLink !</h1>
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia commodi excepturi ipsam magnam aut! Unde vero at consectetur doloremque omnis necessitatibus harum deleniti quasi numquam nulla quisquam eos aliquam vitae illo fuga ex itaque iusto, distinctio quaerat saepe consequuntur nesciunt cumque. Harum qui provident officia eaque sequi eos, tempora non.
        </p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi delectus inventore ipsa, maiores adipisci, iure similique veritatis praesentium cumque eum itaque non quis aperiam perferendis vel necessitatibus impedit quidem eaque, dignissimos quisquam repellendus nostrum. Voluptatum qui earum quae explicabo, quis atque ea tempora est rem corrupti necessitatibus. Atque vero sed quia distinctio, incidunt iusto sapiente odit dignissimos id quibusdam harum praesentium dolores molestias explicabo. Distinctio sequi consequatur nam quasi illum deserunt optio, qui quia corporis quibusdam eligendi, facere modi vel ipsa. Nulla, labore ut, optio hic voluptate beatae saepe aliquam animi minima mollitia vel, magnam reprehenderit quod a exercitationem accusantium.</p>
        <p>Ipsa dolores odio ducimus consectetur exercitationem voluptas error, explicabo amet fugiat quasi adipisci cumque. Sit sapiente, repudiandae libero voluptatem dicta itaque nesciunt. Sapiente nesciunt voluptatibus et hic totam laborum ullam aut ex aspernatur corporis, sit id ducimus, architecto mollitia! Dicta deserunt, eos est numquam voluptates temporibus! Id optio autem consequatur nesciunt nostrum corporis natus excepturi magnam repudiandae deserunt, impedit, sequi vitae suscipit vero perferendis corrupti unde dicta dignissimos eum blanditiis assumenda soluta quod explicabo! Repellat voluptatibus reiciendis, nisi magni beatae voluptatem sed explicabo accusantium pariatur similique ratione id, ipsam tenetur quasi necessitatibus possimus ab error. Porro magni a quidem cupiditate!</p>
        <p>Nihil, deleniti. Doloremque et incidunt dolorem, quisquam earum exercitationem aspernatur qui nihil mollitia vero. Corporis soluta odio vitae possimus similique expedita reprehenderit ad, dolore nisi consequatur quisquam sed quos culpa deleniti commodi reiciendis illo in, delectus voluptatem blanditiis. Dolorum sunt, repudiandae veniam amet dolor dolores pariatur dignissimos facere fuga aspernatur, consequuntur ducimus ipsum vitae laudantium culpa! Rem asperiores officia quas beatae fuga repellat ipsam cum illum iusto corporis nobis ipsum est itaque perspiciatis porro accusantium, earum tenetur tempora quis, provident deleniti expedita quod? Doloribus dolor delectus porro natus facere minus. Officiis vitae minus, officia nesciunt id amet maiores illo labore.</p>
        <p>Ipsum facere earum libero possimus cum quis quidem error voluptatem culpa ratione corporis officiis nesciunt, tempore rerum voluptatum cumque, deserunt, aut facilis voluptatibus dolores optio est sequi repudiandae? Sunt omnis eos assumenda, quae provident recusandae nostrum vero, cum et nemo sapiente, rerum esse suscipit incidunt dolorum. Ipsam, animi nobis eum qui alias quo illum consequatur eveniet excepturi quos reprehenderit quae repudiandae molestias, sapiente corporis, dignissimos minus aliquam consectetur iusto dolor facere explicabo incidunt laborum. Nostrum id ad blanditiis aliquam, repellendus vero repudiandae dicta, autem sequi asperiores sed fuga magnam nisi? Repellat facere quibusdam saepe rem est autem sapiente ea deserunt?</p>
        <p>Unde et enim consequatur modi, voluptate velit a at. Ratione corrupti distinctio, facere, suscipit, error molestiae magnam deleniti asperiores saepe sit quibusdam tempora? Consequatur atque culpa deleniti quaerat quam? Qui error impedit blanditiis, est iure delectus non, architecto voluptate aliquam, ipsa earum. Aliquid, molestiae perferendis voluptas id reiciendis quas tempore, debitis impedit, quibusdam laudantium pariatur provident ipsum. Atque, amet nesciunt cum aliquid iure ipsam, illum hic quis aspernatur quod quidem illo odio. Commodi beatae quis, officia doloribus quos ratione cum debitis ex dolor ea autem veritatis deleniti consequuntur odit suscipit soluta? Tenetur similique qui ab deserunt a voluptatum facere soluta!</p>
        <p>A libero tenetur quaerat eligendi nobis iusto expedita! Optio, iusto. Commodi laborum sint distinctio facere porro explicabo cumque, debitis necessitatibus nulla perspiciatis recusandae pariatur dolore. Fugiat odio dolores, laborum sunt voluptate veritatis maiores sapiente libero deserunt. Nesciunt id debitis delectus consequatur animi cumque inventore voluptates reiciendis odio sunt maxime vel quo, ea eum iusto quod eos corrupti. Quisquam quam rerum eum quasi esse enim molestias nulla at error voluptas, magnam aliquid hic veritatis expedita perspiciatis recusandae quibusdam! Nemo sequi impedit maiores, velit architecto exercitationem laborum qui! Tempore sapiente explicabo, ducimus quo non, saepe laudantium quidem, corrupti asperiores iusto ex optio!</p>
        <p>Aperiam debitis mollitia molestiae cum, quis sit repellendus fugit molestias rerum voluptatibus autem impedit a dicta nihil odio distinctio inventore tenetur repudiandae odit aliquam, alias omnis quisquam culpa? Necessitatibus, nemo corrupti. Reprehenderit itaque laudantium impedit totam, beatae ullam nesciunt dolorum quae, dignissimos iusto veritatis tempora animi id magni aliquam error voluptate laboriosam quas earum debitis hic ipsam. Ut voluptatum fuga facilis nostrum ab, eligendi obcaecati ipsa alias! Assumenda perspiciatis, saepe neque quos id iste eligendi quisquam nemo nesciunt nulla sint doloremque aliquid dignissimos consectetur atque officia? Consequuntur est suscipit optio, commodi reiciendis fugit expedita omnis placeat vero. Quos, non placeat?</p>
        <p>Soluta molestiae, ipsam illo excepturi accusamus alias voluptate doloremque odio fugiat libero? Aperiam odit facilis et? Ea facere, nisi vero possimus in dolor atque totam itaque aperiam, voluptatibus illum omnis hic corrupti! Non facere cum rerum ipsa odit optio rem commodi distinctio necessitatibus obcaecati! Voluptas vel sit quis, velit at voluptatum ducimus. Unde accusantium est sunt quam repellat non quibusdam porro adipisci minus tempore nemo omnis sit magni ipsa suscipit, itaque modi quod quas quo eius sequi aut eveniet. Quam porro ratione vero tempora ut quod architecto dolore quibusdam maxime aperiam fugiat molestiae nam voluptatum vitae, esse culpa suscipit placeat!</p>
        <p>Maiores nemo exercitationem voluptatem, eaque ullam omnis ea corporis quo quae earum, nostrum a! Explicabo quidem hic sed iusto id quasi cum blanditiis eos quisquam a voluptates labore tenetur iste commodi corrupti veniam, odio delectus provident quos. Ad placeat, aspernatur minus dignissimos eum culpa soluta laudantium quam nam omnis quod, cumque, earum nulla neque commodi sint? Repudiandae, dolorem voluptates facilis voluptatem, est quo libero accusantium debitis, cumque quos quibusdam soluta! Dolorem harum nemo impedit dolore, vel voluptatum quis tenetur molestiae itaque corporis at, blanditiis corrupti. Rerum libero odio voluptas nisi vel vero illo, tenetur molestiae ut, aut officia consequuntur earum.</p>
        <p>Magni error laudantium ipsum tempora autem officiis, eveniet minus dignissimos provident nulla! Maiores, rerum nemo esse sapiente fuga, iure aspernatur inventore veritatis voluptate architecto placeat accusantium hic. Aut ducimus nulla, labore iusto totam consequuntur officiis ut fugiat ipsum accusantium nesciunt. Adipisci alias modi ex voluptatem doloremque voluptatum minima illo accusantium fugiat! Minima quo hic nemo! Atque ex velit iure molestiae numquam officia qui praesentium distinctio, voluptates sunt fuga delectus animi repellat veniam reiciendis quasi soluta repellendus, neque facere iusto nemo? Perspiciatis consequuntur, rerum debitis consectetur tenetur deserunt eaque odio perferendis odit, pariatur in eveniet magnam corporis nisi cupiditate, vitae quibusdam.</p>
    </main>
    <?php require_once "footer.php" ?>
</body>
</html>